import { Alexandria } from "next/font/google";
import "./globals.css";

const geistSans = Alexandria({

  subsets: ["latin"],
  variable: '--font-DM',
});



export const metadata = {
  title: "onboarding challenge",
  description: "Generated by mohammed sobhi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
